# Generated by Django 4.1.6 on 2023-02-03 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canvas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="x",
            field=models.BigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-10000),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="y",
            field=models.BigIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(-10000),
                    django.core.validators.MaxValueValidator(10000),
                ],
            ),
        ),
    ]
