version: '3.8'

services:
  backend-django:
    build: ./src/backend/workflow23
    command: bash -c " python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./src/backend/workflow23:/app
      - static_volume:/app/static
    env_file:
      - .backend.env
    networks:
      - memefeed-network
  frontend:
    build: ./src/frontend
    command: node src/app.js
    ports:
      - 8888:8888
    volumes:
      - ./src/frontend:/app
      - static_volume:/app/static
    networks:
      - memefeed-network



volumes:
  static_volume:
networks:
  memefeed-network:
  
